name: Go tests

on:
  push:
    branches:
      - main
      - lab_02

jobs:
  lint:
      runs-on: ubuntu-latest
      environment: test-env

      steps:
        - name: Install Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.23

        - name: Check out repository
          uses: actions/checkout@v2
        
        - name: Install golintIn and go vet
          run: |
            go install github.com/rauzh/go-complexity-analysis/cmd/complexity@9a7cad4
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest


        - name: Launch govet
          run: |
            go vet -vettool="$(which complexity)" --cycloover 10 --halsteadover 40 ./internal/domain/album/... 
            if [ $? -ne 0 ]; then exit 1; fi

        - name: Launch golint
          run: |
            golangci-lint run ./...
            if [ $? -ne 0 ]; then exit 0; fi
  
  build_and_test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Run unit tests
        run: make -C . ci-unit

      - name: Run integration tests
        run: make -C . ci-integration

      - name: Run E2E tests
        run: make -C . ci-e2e

      - name: Processing report data
        run: make -C . ci-concat-reports -i
        if: always()
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-reports
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-reports
